[package]
name = "technobot"
version = "0.1.0"
authors = ["Jacob Helwig <jacob@technosorcery.net>"]

[dependencies]
rand = "0.3.16"
chrono = "0.4.0"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity"
features = ["cache", "framework", "standard_framework"]
